apiVersion: batch/v1
kind: Job
metadata:
    name: gpt2-pytorch-job
    labels:
        kueue.x-k8s.io/queue-name:  eidf114ns-user-queue
spec:
    completions: 1
    template:
        metadata:
            name: gpt2-pytorch-pod
        spec:
            restartPolicy: Never
            containers:
            - name: gpt2-pytorch-con
              image: charaka/transformers_pytorch:v1.0-transformers
              command: ["python3"]
              args: ["/mnt/ceph_rbd/ClicheSentenceCreator.py", "/mnt/ceph_rbd/cliche_sentences.txt"]
              volumeMounts:
                - mountPath: /mnt/ceph_rbd
                  name: volume
              resources:
                requests:
                  cpu: 2
                  memory: "1Gi"
                limits:
                  cpu: 4
                  memory: "4Gi"
                  nvidia.com/gpu: 1
            nodeSelector:
                nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB-MIG-1g.5gb
            volumes:
                - name: volume
                  persistentVolumeClaim:
                    claimName: gpt2-pytorch-pvc

